From openjdk:8

MAINTAINER Santosh Kumar Rajaguru <sanit4u@gmail.com>

copy ./target/check-service-0.0.1-SNAPSHOT-spring-boot.jar check-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","check-service-0.0.1-SNAPSHOT.jar"]