From openjdk:8

MAINTAINER Santosh Kumar Rajaguru <sanit4u@gmail.com>

copy ./target/exchange-service-0.0.1-SNAPSHOT.jar exchange-service-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","exchange-service-0.0.1-SNAPSHOT.jar"]